### ISSUE TITLE
Cannot access bintray repo anymore

### ISSUE THREAD

**Issue by nbenns** [StreetContxt/kpl-scala#14]
It looks like bintray has shutdown.
Is there an alternate resolver that can be used to get this dependency?

**Comment by agenovese** [comment]
Hi, Bintray has shut down. We've migrated to Sonatype/Maven Central for hosting, apologies as I apparently missed updating the README.

The latest version is available at "io.github.streetcontxt" %% "kpl-scala" % "2.0.0"
